image: rafahsolis/djangosecure_runner:0.0.0

test:
  tags:
  - docker_python2.7

  before_script:
  - apt-get install apt-get install python-dev libgmp-dev gcc

  script:
  - pip install -r requirements.txt
  - nosetests --with-coverage --cover-erase --cover-package=. --cover-html

  artifacts:
    paths:
    - cover