image: rafahsolis/djangosecure_runner

test:
  tags:
  - docker_python2.7

  script:
  - pip install -r requirements_test.txt
  - nosetests --with-coverage --cover-html --cover-inclusive --cover-package=djangosecure

  artifacts:
    paths:
    - cover